/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package example;

import java.awt.AWTException;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.io.File;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author schel
 */
public class Teste extends javax.swing.JFrame {

    /**
     * Creates new form Teste
     */
    public Teste() {
        initComponents();
        this.setName("SlidePictures");
        this.setIconImage(new ImageIcon(getClass().getResource("/imagens/monitor.png")).getImage());
        //URL url = this.getClass().getResource("/imagens/slide.png");
        //Icon img = new ImageIcon(Toolkit.getDefaultToolkit().getImage(url));
        //jLabel1.setIcon(img);
        inicial();
        resize();
        leitura();
        tempo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1368, 768));
        setMinimumSize(new java.awt.Dimension(1368, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1368, 768));
        setSize(new java.awt.Dimension(1368, 768));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setAlignmentY(0.0F);
        jLabel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jLabel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        tempo.stop();

        String textoDoJPane = JOptionPane.showInputDialog(null, "Intervalo em segundos:", (intervalo / 1000));
        if (textoDoJPane != null) {
            boolean validaNumero = false;
            for (int i = 0; i < textoDoJPane.length(); i++) {
                if (Character.isDigit(textoDoJPane.charAt(i))) {
                    validaNumero = true;
                } else {
                    validaNumero = false;
                    JOptionPane.showMessageDialog(null, "Digite apenas números!");
                    textoDoJPane = JOptionPane.showInputDialog(null, "Intervalo em segundos:", (intervalo / 1000));
                }
            }
            intervalo = 1000 * Integer.parseInt(textoDoJPane);
            if (intervalo < 2000) {
                intervalo = 2000;
            }
        }
        System.out.println("intervalo " + intervalo + " milisegundos");
        tempo();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
            System.exit(0);
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teste().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
public List imagens = new ArrayList();
    Timer tempo;
    boolean tmp = false;
    int item = 0;
    int intervalo = 2000;
    int width = 1366;
    int height = 768;

    private void slide() {

        item++;
        if (item > imagens.size() - 1) {
            item = 0;
            leitura();
        }

        try {
            jLabel1.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage((String) imagens.get(item)).getScaledInstance(width, height, Image.SCALE_SMOOTH)));

        } catch (IndexOutOfBoundsException e) {
            inicial();
        }
        //jLabel1.repaint();
        //pack();
        System.out.println(item);

    }

    private void leitura() {
        imagens.clear();
        File arquivo = new File("c:\\SlidePictures\\");
        File[] file = arquivo.listFiles();

        if (file != null) {
            int length = file.length;

            for (int i = 0; i < length; ++i) {
                File f = file[i];

                if (f.isFile()) {
                    System.out.println(f.getName());
                    if (!f.getName().equals("Thumbs.db")) {
                        imagens.add("c:/SlidePictures/" + f.getName());
                    }
                }
            }

        } else {
            inicial();
        }

    }

    private void resize() {
        Toolkit kit = Toolkit.getDefaultToolkit();
        Dimension tamTela = kit.getScreenSize();

        //Pega largura e altura da tela 
        width = tamTela.width;
        height = tamTela.height;

        /* larg x 0.7; para ocupar 70% da tela por exemplo  */
 /* alt x 0.7;*/
        //Manda o JFrame utilizar suas dimensões  
        setSize(width, height);
        getContentPane().add(jLabel1);
        //jLabel1.setLocation(0, 0);
        //jLabel no tamanho da tela
        jLabel1.setSize(tamTela);

    }

    private void tempo() {
        tempo = new Timer(intervalo, (ActionEvent e) -> {
            slide();
            mouseMove();
        } //vai esperar intervalo e executar essa ação
        );
        tempo.start();
    }

    private void inicial() {
        URL url = this.getClass().getResource("/imagens/slide.png");
        Icon img = new ImageIcon(Toolkit.getDefaultToolkit().getImage(url));
        jLabel1.setIcon(img);
    }

    private void mouseMove() {
        Robot robot;
        try {
            robot = new Robot();
            int X = MouseInfo.getPointerInfo().getLocation().x;
            int Y = MouseInfo.getPointerInfo().getLocation().y;
            if (X > width-2) {
                X = 1;
            }
            robot.mouseMove(X + 1, Y);
        } catch (AWTException ex) {
            Logger.getLogger(Teste.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
